"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import environ
import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

#load_dotenv(os.path.join(BASE_DIR, '.env'))

# Load .env file
"""env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '../../.env'))"""


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-devj^eh7xu13c0fy0nm+b)v*vir2)@o=@=qh5!@&s0s9yy5eb='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'attendance',
    'leaves',
    'payslips',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'attendance.context_processors.approval_counts',
                'leaves.context_processors.pending_approvals_count'
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

LOGIN_REDIRECT_URL = '/user/dashboard/'
LOGOUT_REDIRECT_URL = '/login/'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
LOGIN_URL = '/login/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Media files (Uploaded by users)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ===== EMAIL CONFIGURATION FOR LEAVES =====
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# ===== EMAIL CONFIGURATION FOR LEAVES USING OUTLOOK EMAIL=====
"""EMAIL_HOST = 'smtp.office365.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
SERVER_EMAIL = EMAIL_HOST_USER
SITE_URL = os.getenv('SITE_URL')"""

# AWS SES SMTP settings
EMAIL_HOST = f"email-smtp.{os.getenv('SES_REGION', 'ap-south-1')}.amazonaws.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# AWS SES SMTP credentials (from .env)
EMAIL_HOST_USER = os.getenv('SES_SMTP_USER')
EMAIL_HOST_PASSWORD = os.getenv('SES_SMTP_PASS')

# From email (must be verified in SES)
DEFAULT_FROM_EMAIL = os.getenv('SES_FROM_EMAIL')
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# Leave Management
LEAVE_MANAGER_EMAIL = os.getenv('LEAVE_MANAGER_EMAIL')

# ===== LEAVE REQUEST CONFIGURATION =====
LEAVE_MANAGERS = {
    'hr': {
        'name': 'HR Manager',
        'email': 'divyang.datania@thenewsmarket.com'  
    },
    'manager': {
        'name': 'Your Manager',
        'email': 'divyang.datania@thenewsmarket.com'  
    }
}

LEAVE_APPROVER = {
    'name': 'HR Director',
    'email': 'divyang.datania@thenewsmarket.com',  
    'title': 'Director'
}

# Email template settings
EMAIL_TEMPLATE_PREFIX = 'emails/'
EMAIL_PLAIN_TEXT = False  # Use HTML emails
