# Generated by Django 6.0 on 2025-12-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_leaves',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='used_leaves',
            field=models.IntegerField(default=0),
        ),
    ]
