# Generated by Django 5.2.8 on 2026-01-02 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_total_leaves_profile_used_leaves'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='used_leaves',
        ),
    ]
