# Generated by Django 6.0 on 2025-12-31 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_leaverequest_created_at_leaverequest_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='duration',
            field=models.CharField(choices=[('full', 'Full Day'), ('first_half', 'First Half (Morning)'), ('second_half', 'Second Half (Afternoon)')], default='full', max_length=20),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('Casual', 'Casual Leave'), ('Sick', 'Sick Leave'), ('Earned', 'Earned Leave'), ('Maternity', 'WMaternity Leave'), ('WFH', 'Work From Home'), ('Other', 'Other')], max_length=10),
        ),
    ]
