# Generated by Django 5.2.8 on 2026-01-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_leaverequest_duration_alter_leaverequest_leave_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='duration',
            field=models.CharField(choices=[('full', 'Full Day'), ('first_half', 'First Half'), ('second_half', 'Second Half')], default='full', max_length=20),
        ),
    ]
