# Generated by Django 6.0 on 2026-01-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0004_alter_leaverequest_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='email_sent_to_employee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='email_sent_to_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='manager_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
