# Generated by Django 6.0 on 2025-12-30 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_absencetype_department_absence_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='absence',
            name='attendance__employe_fed211_idx',
        ),
        migrations.RemoveIndex(
            model_name='absence',
            name='attendance__start_d_22f5f2_idx',
        ),
        migrations.RemoveField(
            model_name='absence',
            name='absence_type',
        ),
        migrations.RemoveField(
            model_name='absence',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='absence',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='absence',
            name='requested_by',
        ),
        migrations.DeleteModel(
            name='AbsenceApprovalWorkflow',
        ),
        migrations.DeleteModel(
            name='AbsenceType',
        ),
        migrations.DeleteModel(
            name='Absence',
        ),
    ]
